### ISSUE TITLE
Find out if caipora can replace console in the global object

### ISSUE THREAD

**Issue by debugmaster** [debugmaster/caipora#1]
Although its need is questionable, some people have complained that adding a single line to every file using `console` is cumbersome. Moreover, if dependencies are using `global.console`, they could (or should) be affected by `caipora` as well.

**Comment by debugmaster** [comment]
For instance, two scenarios cannot be replaced:

1. When `require("console")` is used instead of global `console`.
2. For `Console` instances that were created before replacing `console` with `caipora`.

**Comment by cmoreira-daitan** [comment]
This is fixed in version 1.2.0. If you load/import the library with "caipora/register", it will replace the global console object.

You could undo it by importing "caipora/unregister" although not likely.

**Comment by debugmaster** [comment]
This has been implemented in `1.2.0`. However, it seems to start to work for NodeJS v10. Still investigating how to support this in v8 or older versions.

**Comment by debugmaster** [comment]
It's working from NodeJS v6 to v12 in `1.2.1`.
